### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by learnwithalfred** [learnwithalfred/backend-microverse-final-capstone#9]
## Link to project 

https://github.com/users/learnwithalfred/projects/12

## Number of people in group =  5

# Screenshot of Kanban board

<img width="1671" alt="Screenshot 2022-11-30 at 09 46 42" src="https://user-images.githubusercontent.com/34389326/204762915-30588b46-794a-4dba-bf74-2b3e1e7466ae.png">

**Comment by Meltrust** [comment]
Hi @learnwithalfred,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Kindly, be more specific on your cards, I'm talking about this one:

![image](https://user-images.githubusercontent.com/57421823/204767567-9f9373b5-47f0-46f3-b630-057df0faa82f.png)

Also, the API documentation and tests are missing from your cards.

## Explanation

This task involves almost all the backend app, and could be easily separated into at least 2-3.  If you also include the tests and the docs, the task would be even bigger (a lot more than 3 points).

## Tips and extra help

- The models-controllers
- The routes
- The tests
- The API docs (tip: [Swagger](https://github.com/rswag/rswag) tests will create the docs automatically for you),
- Remember that the Frontend must be responsive.
- As per the project requirements, please ensure that no single member has a lot more work than the others.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dodoburner** [comment]
@Meltrust Thanks Miguel, I have divided the backend more thoroughly and added a card for the tests which will be divided by each of us equally.

**Comment by Meltrust** [comment]
Hi @learnwithalfred,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!






## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
